spring:
  jpa:
    database: mysql
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/ddd_start?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: root
    password: Qwpo1209!@
    driver-class-name: com.mysql.cj.jdbc.Driver
password:
  secretKey: TaeWooTaeWooSecretKey