version: "3.7"

services: 
  mysql:
    image: mysql:5.7
    volumes: 
      - ./mysql/:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ddd_start
