version: "3.7"

services:
  mysql:
    env_file:
      - ./.env.docker
    image: mysql:5.7
    platform: linux/amd64
    volumes: 
      - ./mysql/:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ddd_start
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
